// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mdlqpxcqdzwzdypazqkp.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbHFweGNxZHp3emR5cGF6cWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE4NTcwNjMsImV4cCI6MjA0NzQzMzA2M30.WMWz0PtD_uXO2bBTBBW7I_quLAvfLMS-Ka00yUoWCDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);